FROM golang:1.24.3-alpine

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/lib/pq

RUN mkdir -p test-results

CMD ["go", "test", "-v", "./tests/integration/...", "-timeout", "5m"]